# fly.toml app configuration file generated for fly-pi-bb on 2025-11-10T21:36:55+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-pi-bb'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

#[[services]]
#  protocol = 'tcp'
#  internal_port = 3000

#  [[services.ports]]
#    port = 3000

#  [[services.ports]]
#    port = 443
#    handlers = ['tls']

#  [services.concurrency]
#    hard_limit = 25
#    soft_limit = 20

#  [[services.tcp_checks]]
#    interval = '10s'
#    timeout = '2s'

#[[services]]
#  protocol = 'tcp'
#  internal_port = 53

#  [[services.ports]]
#    port = 53

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
